# Generated by Django 3.1.7 on 2021-03-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_date', models.TextField()),
                ('tracking_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=40)),
                ('supplier_email', models.CharField(max_length=30)),
                ('supplier_contact', models.CharField(max_length=11)),
            ],
        ),
    ]
