# Generated by Django 3.1.7 on 2021-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.IntegerField()),
            ],
        ),
    ]
