# Generated by Django 3.1.7 on 2021-03-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_Title', models.TextField()),
                ('crs_code', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.teacher')),
            ],
        ),
    ]
