# Generated by Django 3.1.7 on 2021-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('delivary_charge', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('transport_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
